# We have to pass `sources`, so minimize the number of files that are scanned
sources:
  - ../templates
templates:
  - ../templates/AppSecrets.stencil
output:
  ../../{{cookiecutter.project_dir}}/Application
args:
  foo: ${FOO}
