# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# Basic
def basic_pods
    # ...
end

# Testing
def test_pods
  pod 'SnapshotTesting', '~> 1.9'
end

# UITesting
def ui_test_pods
  pod 'Swifter', '~> 1.5.0'
end

target '{{cookiecutter.project_name}}' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Adequate
  basic_pods
end

target '{{cookiecutter.project_name}}Tests' do
  use_frameworks!
  basic_pods
  test_pods
end

target '{{cookiecutter.project_name}}UITests' do
  use_frameworks!
  ui_test_pods
end
