app_identifier "{{ cookiecutter.bundle_identifier }}"

copyright "#{Time.now.year} {{ cookiecutter.company_name }}"

# app_rating_config_path "./fastlane/metadata/rating_config.json"

# price_tier 0 # free app

# Comes from https://github.com/fastlane/fastlane/issues/5542#issuecomment-254201994
submission_information({
    # Ads
    # add_id_info_limits_tracking: true,
    # add_id_info_serves_ads: false,
    # add_id_info_tracks_action: false,
    # add_id_info_tracks_install: false,
    # add_id_info_uses_idfa: false,
    #
    # content_rights_has_rights: true,
    # content_rights_contains_third_party_content: false,
    # Export Compliance
    # export_compliance_platform: 'ios',
    # export_compliance_compliance_required: false,
    # export_compliance_encryption_updated: false,
    # export_compliance_app_type: nil,
    # export_compliance_uses_encryption: false,
    # export_compliance_is_exempt: false,
    # export_compliance_contains_third_party_cryptography: false,
    # export_compliance_contains_proprietary_cryptography: false,
    # export_compliance_available_on_french_store: false
})

# ipa("./fastlane/builds/{{ cookiecutter.project_name }}.ipa")

# submit_for_review(true)

# automatic_release(false)

# force(true) # Skip HTML preview verification before actual upload
